name = "one"
description = ""
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["one"]

[[depends-on]]
aunit = "^26.0.0"

[[depends-on]]
libadalang_tools = "^26.0.0"

[[actions]]
type = "test"
command = ["alr", "exec", "--", "gprbuild", "-P", "test/test.gpr"]

[[actions]]
type = "test"
command = ["./bin/test_runner"]
