name: n
    n: 1
    type: int
    help: Exact number of lines in stdin to filter.
    default: 1

# name: n_context
#     n: 1
#     type: int
#     help: How many lines of context to give in case there are errors.

name: help
    n: 0
    type: int
    help: Print help and exit.

name: version
    n: 0
    type: int
    help: Print version and exit.
