name: n
    n: 1
    description: Exact number of lines in stdin to filter.
    default: 1

name: empty
    n: 0
    description: Fail if stdin is not empty.

# name: n_context
#     n: 1
#     description: How many lines of context to give in case there are errors.

name: help
    n: 0
    description: Print help and exit.

name: version
    n: 0
    description: Print version and exit.
