#! /usr/bin/env bash

# Halt on error.
set -euo pipefail

# Go to execution directory.
cd "$(git rev-parse --show-toplevel)"
test -d ./.git

make dev check test

# vim: set filetype=sh fileformat=unix nowrap:
